#
# add-export-and-delete-data-feature.ps1
# --------------------------------------
# Run this from: D:\Rozmarrah-CUST\Saim Ashraf\Nimko\Working\Code\GhaniFoods
#
# Adds:
#   1. Storage bucket migration for "exports" bucket
#   2. Backend edge function: data-export (CSV / XLSX / PDF / DOCX, with
#      module selection + optional date range)
#   3. Backend edge function: data-delete (deletes ONLY business data,
#      never touches auth/admin users; auto-backs-up to xlsx first;
#      requires typed confirmation phrase)
#   4. Frontend components: ExportDataPanel, DangerZonePanel
#   5. Wires both panels into the Settings page
#
# IMPORTANT: TABLE_MAP / DELETE_ORDER inside the two edge functions use
# guessed table names (raw_materials, receipts, batches, customers,
# invoices, payments, suppliers, wrappers, boxes, carton_configurations,
# finished_cartons). If your actual schema (0001_init_schema.sql) uses
# different table/column names, edit those two files after this script
# runs, before deploying.
#
# Also installs npm deps in apps/backend is NOT needed (Supabase edge
# functions use npm: specifiers resolved by Deno at deploy time - no
# local npm install required for the edge functions themselves).
#
# Safe to re-run - already-applied files are skipped where sensible.
# Backups made before any edit: <file>.bak-<timestamp>
#

$ErrorActionPreference = "Stop"
$root = Get-Location
$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
Write-Host "Running in: $root" -ForegroundColor Cyan

function Backup-File($path) {
    if (Test-Path -LiteralPath $path) {
        Copy-Item -LiteralPath $path -Destination "$path.bak-$stamp"
        Write-Host "  Backed up -> $(Split-Path $path -Leaf).bak-$stamp" -ForegroundColor DarkGray
    }
}

function Ensure-Dir($path) {
    if (-not (Test-Path -LiteralPath $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
    }
}

$migrationSql = @'
-- Creates a private storage bucket for generated export files (csv/xlsx/pdf/docx).
-- Files are short-lived: accessed via signed URLs generated by the data-export function.

insert into storage.buckets (id, name, public)
values ('exports', 'exports', false)
on conflict (id) do nothing;

-- Allow the service role (used inside edge functions) full access.
-- Edge functions use the service role key, so no additional policy is
-- strictly required for them, but we add explicit policies for clarity
-- and in case authenticated users are ever given direct access later.

drop policy if exists "Service role manages exports" on storage.objects;
create policy "Service role manages exports"
  on storage.objects
  for all
  to service_role
  using (bucket_id = 'exports')
  with check (bucket_id = 'exports');

'@

$exportFnTs = @'
// apps/backend/supabase/functions/data-export/index.ts
//
// Exports GhaniFoods business data as CSV, XLSX, PDF, or DOCX.
// Request body:
// {
//   modules: string[],              // keys from TABLE_MAP, or ["all"]
//   format: "csv" | "xlsx" | "pdf" | "docx",
//   dateRange?: { from?: string; to?: string }   // "YYYY-MM-DD", applied to date-bearing tables
// }
//
// Response: { downloadUrl: string, fileName: string }

import { createClient } from "npm:@supabase/supabase-js@2";
import ExcelJS from "npm:exceljs@4";
import { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, WidthType } from "npm:docx@9";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1";
import { corsHeaders } from "../_shared/cors.ts";

// ---------------------------------------------------------------------
// IMPORTANT: adjust these to match your real schema (see 0001_init_schema.sql)
// key = module name shown in the UI, value = { table, dateColumn? }
// ---------------------------------------------------------------------
const TABLE_MAP: Record<string, { table: string; dateColumn?: string }> = {
  rawMaterials: { table: "raw_materials" },
  suppliers: { table: "suppliers" },
  receipts: { table: "receipts", dateColumn: "purchase_date" },
  receiptLines: { table: "receipt_lines" },
  batches: { table: "batches", dateColumn: "created_at" },
  customers: { table: "customers" },
  invoices: { table: "invoices", dateColumn: "invoice_date" },
  invoiceLines: { table: "invoice_lines" },
  payments: { table: "payments", dateColumn: "payment_date" },
  wrappers: { table: "wrappers" },
  boxes: { table: "boxes" },
  cartonConfigurations: { table: "carton_configurations" },
  finishedCartons: { table: "finished_cartons" },
};

const PROJECT_NAME = "GhaniFoods";

function humanize(key: string) {
  return key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase());
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceKey);

    const body = await req.json();
    let { modules, format, dateRange } = body as {
      modules: string[];
      format: "csv" | "xlsx" | "pdf" | "docx";
      dateRange?: { from?: string; to?: string };
    };

    if (!modules || modules.length === 0 || modules[0] === "all") {
      modules = Object.keys(TABLE_MAP);
    }
    modules = modules.filter((m) => TABLE_MAP[m]);

    if (modules.length === 0) {
      return new Response(JSON.stringify({ error: "No valid modules requested" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ---------------------------------------------------------------
    // 1. Fetch data for each module
    // ---------------------------------------------------------------
    const datasets: { key: string; label: string; rows: Record<string, unknown>[] }[] = [];

    for (const key of modules) {
      const { table, dateColumn } = TABLE_MAP[key];
      let query = supabase.from(table).select("*");

      if (dateColumn && dateRange?.from) query = query.gte(dateColumn, dateRange.from);
      if (dateColumn && dateRange?.to) query = query.lte(dateColumn, dateRange.to);

      const { data, error } = await query;
      if (error) throw new Error(`Failed to fetch ${table}: ${error.message}`);

      datasets.push({ key, label: humanize(key), rows: data ?? [] });
    }

    const generatedAt = new Date().toISOString();
    const rangeNote =
      dateRange?.from || dateRange?.to
        ? `Date range: ${dateRange?.from ?? "start"} to ${dateRange?.to ?? "today"}`
        : "Date range: all time";

    // ---------------------------------------------------------------
    // 2. Build the file
    // ---------------------------------------------------------------
    let fileBytes: Uint8Array;
    let ext: string;
    let contentType: string;

    if (format === "csv") {
      // If multiple modules, we zip-less concat with section headers (simplest, no extra dependency).
      const parts: string[] = [];
      for (const ds of datasets) {
        parts.push(`# ${ds.label}`);
        if (ds.rows.length === 0) {
          parts.push("(no data)");
        } else {
          const headers = Object.keys(ds.rows[0]);
          parts.push(headers.join(","));
          for (const row of ds.rows) {
            parts.push(
              headers
                .map((h) => {
                  const v = row[h];
                  const s = v === null || v === undefined ? "" : String(v);
                  return `"${s.replace(/"/g, '""')}"`;
                })
                .join(","),
            );
          }
        }
        parts.push("");
      }
      fileBytes = new TextEncoder().encode(parts.join("\n"));
      ext = "csv";
      contentType = "text/csv";
    } else if (format === "xlsx") {
      const workbook = new ExcelJS.Workbook();
      workbook.creator = PROJECT_NAME;
      workbook.created = new Date();

      for (const ds of datasets) {
        const sheet = workbook.addWorksheet(ds.label.slice(0, 31)); // Excel sheet name limit
        if (ds.rows.length > 0) {
          const headers = Object.keys(ds.rows[0]);
          sheet.addRow(headers).font = { bold: true };
          for (const row of ds.rows) sheet.addRow(headers.map((h) => row[h] ?? ""));
          sheet.columns.forEach((col) => (col.width = 18));
        } else {
          sheet.addRow(["(no data)"]);
        }
      }

      const buf = await workbook.xlsx.writeBuffer();
      fileBytes = new Uint8Array(buf as ArrayBuffer);
      ext = "xlsx";
      contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    } else if (format === "docx") {
      const children: Paragraph[] = [
        new Paragraph({ text: PROJECT_NAME, heading: HeadingLevel.TITLE }),
        new Paragraph({ text: "Data Export Report" }),
        new Paragraph({ text: `Generated: ${generatedAt}` }),
        new Paragraph({ text: rangeNote }),
        new Paragraph({ text: "" }),
      ];

      const content: (Paragraph | Table)[] = [...children];

      for (const ds of datasets) {
        content.push(new Paragraph({ text: ds.label, heading: HeadingLevel.HEADING_1 }));
        if (ds.rows.length === 0) {
          content.push(new Paragraph({ text: "(no data)" }));
          continue;
        }
        const headers = Object.keys(ds.rows[0]);
        const rows = [
          new TableRow({
            children: headers.map(
              (h) =>
                new TableCell({
                  width: { size: 100 / headers.length, type: WidthType.PERCENTAGE },
                  children: [new Paragraph({ text: h, heading: HeadingLevel.HEADING_5 })],
                }),
            ),
          }),
          ...ds.rows.map(
            (row) =>
              new TableRow({
                children: headers.map(
                  (h) =>
                    new TableCell({
                      width: { size: 100 / headers.length, type: WidthType.PERCENTAGE },
                      children: [new Paragraph({ text: String(row[h] ?? "") })],
                    }),
                ),
              }),
          ),
        ];
        content.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }));
        content.push(new Paragraph({ text: "" }));
      }

      const doc = new Document({ sections: [{ children: content }] });
      const buf = await Packer.toBuffer(doc);
      fileBytes = new Uint8Array(buf);
      ext = "docx";
      contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    } else if (format === "pdf") {
      const pdfDoc = await PDFDocument.create();
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      const pageWidth = 612;
      const pageHeight = 792;
      const margin = 40;
      const lineHeight = 14;

      let page = pdfDoc.addPage([pageWidth, pageHeight]);
      let y = pageHeight - margin;

      const ensureSpace = () => {
        if (y < margin + lineHeight) {
          page = pdfDoc.addPage([pageWidth, pageHeight]);
          y = pageHeight - margin;
        }
      };

      const drawText = (text: string, opts: { size?: number; bold?: boolean } = {}) => {
        ensureSpace();
        page.drawText(text, {
          x: margin,
          y,
          size: opts.size ?? 10,
          font: opts.bold ? boldFont : font,
          color: rgb(0, 0, 0),
        });
        y -= lineHeight;
      };

      drawText(PROJECT_NAME, { size: 20, bold: true });
      drawText("Data Export Report", { size: 12, bold: true });
      drawText(`Generated: ${generatedAt}`, { size: 9 });
      drawText(rangeNote, { size: 9 });
      y -= lineHeight;

      for (const ds of datasets) {
        drawText(ds.label, { size: 13, bold: true });
        if (ds.rows.length === 0) {
          drawText("(no data)", { size: 9 });
        } else {
          const headers = Object.keys(ds.rows[0]);
          drawText(headers.join(" | "), { size: 8, bold: true });
          for (const row of ds.rows) {
            const line = headers.map((h) => String(row[h] ?? "")).join(" | ");
            drawText(line.slice(0, 140), { size: 8 });
          }
        }
        y -= lineHeight / 2;
      }

      const buf = await pdfDoc.save();
      fileBytes = buf;
      ext = "pdf";
      contentType = "application/pdf";
    } else {
      return new Response(JSON.stringify({ error: "Unsupported format" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ---------------------------------------------------------------
    // 3. Upload to storage, return a signed URL
    // ---------------------------------------------------------------
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const fileName = `${PROJECT_NAME}-export-${timestamp}.${ext}`;
    const path = `exports/${fileName}`;

    const { error: uploadError } = await supabase.storage
      .from("exports")
      .upload(path, fileBytes, { contentType, upsert: true });
    if (uploadError) throw new Error(`Upload failed: ${uploadError.message}`);

    const { data: signed, error: signError } = await supabase.storage
      .from("exports")
      .createSignedUrl(path, 300); // 5 minutes
    if (signError) throw new Error(`Signed URL failed: ${signError.message}`);

    return new Response(JSON.stringify({ downloadUrl: signed.signedUrl, fileName }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err instanceof Error ? err.message : "Export failed" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

'@

$deleteFnTs = @'
// apps/backend/supabase/functions/data-delete/index.ts
//
// Deletes ALL business data (never auth/admin/user tables).
// Requires an exact confirmation phrase. Makes a full xlsx backup to
// storage before deleting, in case the user needs to recover.
//
// Request body: { confirmationText: string }
// Response: { deleted: Record<string, number>, backupUrl: string }

import { createClient } from "npm:@supabase/supabase-js@2";
import ExcelJS from "npm:exceljs@4";
import { corsHeaders } from "../_shared/cors.ts";

const CONFIRMATION_PHRASE = "DELETE ALL DATA";

// ---------------------------------------------------------------------
// IMPORTANT: adjust table names to match your real schema.
// Order matters: children (tables with foreign keys) must be listed
// BEFORE the parents they reference, so deletes don't violate FK constraints.
// This list intentionally excludes auth.users / any admin / profile tables.
// ---------------------------------------------------------------------
const DELETE_ORDER: string[] = [
  "invoice_lines",
  "invoices",
  "payments",
  "receipt_lines",
  "receipts",
  "batches",
  "wrappers",
  "boxes",
  "carton_configurations",
  "finished_cartons",
  "raw_materials",
  "suppliers",
  "customers",
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceKey);

    const body = await req.json();
    const { confirmationText } = body as { confirmationText: string };

    if (confirmationText !== CONFIRMATION_PHRASE) {
      return new Response(
        JSON.stringify({ error: `Confirmation text must exactly match "${CONFIRMATION_PHRASE}"` }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // -----------------------------------------------------------------
    // 1. Backup everything to xlsx before deleting anything
    // -----------------------------------------------------------------
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "GhaniFoods";
    workbook.created = new Date();

    const snapshots: Record<string, Record<string, unknown>[]> = {};

    for (const table of DELETE_ORDER) {
      const { data, error } = await supabase.from(table).select("*");
      if (error) throw new Error(`Backup fetch failed for ${table}: ${error.message}`);
      snapshots[table] = data ?? [];

      const sheet = workbook.addWorksheet(table.slice(0, 31));
      if (data && data.length > 0) {
        const headers = Object.keys(data[0]);
        sheet.addRow(headers).font = { bold: true };
        for (const row of data) sheet.addRow(headers.map((h) => (row as Record<string, unknown>)[h] ?? ""));
      } else {
        sheet.addRow(["(no data)"]);
      }
    }

    const buf = await workbook.xlsx.writeBuffer();
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const backupPath = `exports/GhaniFoods-pre-delete-backup-${timestamp}.xlsx`;

    const { error: uploadError } = await supabase.storage
      .from("exports")
      .upload(backupPath, new Uint8Array(buf as ArrayBuffer), {
        contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        upsert: true,
      });
    if (uploadError) throw new Error(`Backup upload failed: ${uploadError.message}`);

    const { data: signed, error: signError } = await supabase.storage
      .from("exports")
      .createSignedUrl(backupPath, 3600); // 1 hour - give the user time to grab it
    if (signError) throw new Error(`Backup signed URL failed: ${signError.message}`);

    // -----------------------------------------------------------------
    // 2. Delete, in FK-safe order. Never touches auth/admin tables.
    // -----------------------------------------------------------------
    const deleted: Record<string, number> = {};

    for (const table of DELETE_ORDER) {
      const count = snapshots[table]?.length ?? 0;
      // Delete-all trick: match a condition that's always true for the primary key.
      const { error } = await supabase.from(table).delete().not("id", "is", null);
      if (error) throw new Error(`Delete failed for ${table}: ${error.message}`);
      deleted[table] = count;
    }

    return new Response(JSON.stringify({ deleted, backupUrl: signed.signedUrl }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err instanceof Error ? err.message : "Delete failed" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

'@

$exportPanelTsx = @'
"use client";

import { useState } from "react";
import { toast } from "@/components/ui/toast";
import { createClient } from "@/lib/supabase/client";

const MODULE_OPTIONS: { key: string; label: string }[] = [
  { key: "rawMaterials", label: "Raw Materials" },
  { key: "suppliers", label: "Suppliers" },
  { key: "receipts", label: "Receipts" },
  { key: "batches", label: "Batches" },
  { key: "customers", label: "Customers" },
  { key: "invoices", label: "Invoices" },
  { key: "payments", label: "Payments" },
  { key: "wrappers", label: "Wrappers" },
  { key: "boxes", label: "Boxes" },
  { key: "cartonConfigurations", label: "Carton Configurations" },
  { key: "finishedCartons", label: "Finished Cartons" },
];

const FORMAT_OPTIONS: { key: "csv" | "xlsx" | "pdf" | "docx"; label: string }[] = [
  { key: "csv", label: "CSV" },
  { key: "xlsx", label: "Excel (.xlsx)" },
  { key: "pdf", label: "PDF" },
  { key: "docx", label: "Word (.docx)" },
];

export function ExportDataPanel() {
  const [scope, setScope] = useState<"all" | "custom">("all");
  const [selected, setSelected] = useState<string[]>([]);
  const [format, setFormat] = useState<"csv" | "xlsx" | "pdf" | "docx">("xlsx");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [isExporting, setIsExporting] = useState(false);

  const toggleModule = (key: string) => {
    setSelected((prev) => (prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]));
  };

  const handleExport = async () => {
    if (scope === "custom" && selected.length === 0) {
      toast.error("Select at least one module to export");
      return;
    }
    setIsExporting(true);
    try {
      const supabase = createClient();
      const { data: sessionData } = await supabase.auth.getSession();
      const accessToken = sessionData.session?.access_token;

      const res = await fetch(
        `${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/data-export`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${accessToken}`,
          },
          body: JSON.stringify({
            modules: scope === "all" ? ["all"] : selected,
            format,
            dateRange: fromDate || toDate ? { from: fromDate || undefined, to: toDate || undefined } : undefined,
          }),
        },
      );

      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "Export failed");

      // Trigger download
      const a = document.createElement("a");
      a.href = json.downloadUrl;
      a.download = json.fileName;
      document.body.appendChild(a);
      a.click();
      a.remove();

      toast.success("Export ready — download started");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to export data");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="rounded-xl border border-[var(--surface-border)] bg-[var(--surface)] p-5 space-y-4">
      <div>
        <h2 className="text-lg font-semibold text-[var(--foreground)]">Export Data</h2>
        <p className="text-xs text-[var(--text-faint)] mt-1">
          Download your data as a report. Choose everything or specific modules, an optional date
          range, and a file format.
        </p>
      </div>

      <div className="flex items-center gap-4 text-sm">
        <label className="flex items-center gap-1.5">
          <input type="radio" checked={scope === "all"} onChange={() => setScope("all")} />
          Export all data
        </label>
        <label className="flex items-center gap-1.5">
          <input type="radio" checked={scope === "custom"} onChange={() => setScope("custom")} />
          Select specific data
        </label>
      </div>

      {scope === "custom" && (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {MODULE_OPTIONS.map((m) => (
            <label key={m.key} className="flex items-center gap-1.5 text-xs text-[var(--text-secondary)]">
              <input type="checkbox" checked={selected.includes(m.key)} onChange={() => toggleModule(m.key)} />
              {m.label}
            </label>
          ))}
        </div>
      )}

      <div className="flex flex-wrap items-end gap-3">
        <div>
          <label className="text-xs text-[var(--text-muted)]">From (optional)</label>
          <input
            type="date"
            value={fromDate}
            onChange={(e) => setFromDate(e.target.value)}
            className="mt-1 block rounded-lg border border-[var(--surface-border)] bg-[var(--background)] px-3 py-2 text-sm text-[var(--foreground)] outline-none focus:border-[var(--surface-border-strong)]"
          />
        </div>
        <div>
          <label className="text-xs text-[var(--text-muted)]">To (optional)</label>
          <input
            type="date"
            value={toDate}
            onChange={(e) => setToDate(e.target.value)}
            className="mt-1 block rounded-lg border border-[var(--surface-border)] bg-[var(--background)] px-3 py-2 text-sm text-[var(--foreground)] outline-none focus:border-[var(--surface-border-strong)]"
          />
        </div>
        <div>
          <label className="text-xs text-[var(--text-muted)]">Format</label>
          <select
            value={format}
            onChange={(e) => setFormat(e.target.value as typeof format)}
            className="mt-1 block rounded-lg border border-[var(--surface-border)] bg-[var(--background)] px-3 py-2 text-sm text-[var(--foreground)] outline-none focus:border-[var(--surface-border-strong)]"
          >
            {FORMAT_OPTIONS.map((f) => (
              <option key={f.key} value={f.key}>
                {f.label}
              </option>
            ))}
          </select>
        </div>
        <button
          type="button"
          onClick={handleExport}
          disabled={isExporting}
          className="rounded-lg bg-neutral-900 dark:bg-neutral-50 px-4 py-2 text-sm font-medium text-neutral-50 dark:text-neutral-950 hover:opacity-90 transition-opacity disabled:opacity-50"
        >
          {isExporting ? "Exporting..." : "Export"}
        </button>
      </div>
    </div>
  );
}

export default ExportDataPanel;

'@

$dangerPanelTsx = @'
"use client";

import { useState } from "react";
import { toast } from "@/components/ui/toast";
import { createClient } from "@/lib/supabase/client";

const CONFIRMATION_PHRASE = "DELETE ALL DATA";

export function DangerZonePanel() {
  const [modalOpen, setModalOpen] = useState(false);
  const [confirmText, setConfirmText] = useState("");
  const [acknowledged, setAcknowledged] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  const canConfirm = confirmText === CONFIRMATION_PHRASE && acknowledged && !isDeleting;

  const closeModal = () => {
    setModalOpen(false);
    setConfirmText("");
    setAcknowledged(false);
  };

  const handleDelete = async () => {
    if (!canConfirm) return;
    setIsDeleting(true);
    try {
      const supabase = createClient();
      const { data: sessionData } = await supabase.auth.getSession();
      const accessToken = sessionData.session?.access_token;

      const res = await fetch(
        `${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/data-delete`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${accessToken}`,
          },
          body: JSON.stringify({ confirmationText: confirmText }),
        },
      );

      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "Delete failed");

      // Offer the backup download
      const a = document.createElement("a");
      a.href = json.backupUrl;
      a.download = "";
      document.body.appendChild(a);
      a.click();
      a.remove();

      const totalDeleted = Object.values(json.deleted as Record<string, number>).reduce(
        (sum, n) => sum + n,
        0,
      );
      toast.success(`Deleted ${totalDeleted} records. A backup was downloaded.`);
      closeModal();
      // Reload so the app reflects the now-empty state
      window.location.reload();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to delete data");
    } finally {
      setIsDeleting(false);
    }
  };

  return (
    <div className="rounded-xl border border-red-900 bg-red-950/20 p-5 space-y-3">
      <div>
        <h2 className="text-lg font-semibold text-red-400">Danger Zone</h2>
        <p className="text-xs text-red-300/80 mt-1">
          Permanently deletes all business data (raw materials, receipts, batches, customers,
          invoices, payments, packaging, cartons). Your admin login is never affected. A backup
          file is generated and downloaded automatically before deletion.
        </p>
      </div>
      <button
        type="button"
        onClick={() => setModalOpen(true)}
        className="rounded-lg border border-red-800 bg-red-950/40 px-4 py-2 text-sm font-medium text-red-400 hover:bg-red-950/70 transition-colors"
      >
        Delete All Data
      </button>

      {modalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
          <div className="w-full max-w-sm rounded-xl border border-red-900 bg-[var(--surface)] p-5 space-y-4">
            <h3 className="text-base font-semibold text-red-400">Confirm permanent deletion</h3>
            <p className="text-xs text-[var(--text-secondary)]">
              This cannot be undone. Type <span className="font-mono font-semibold">{CONFIRMATION_PHRASE}</span> to
              confirm.
            </p>
            <input
              value={confirmText}
              onChange={(e) => setConfirmText(e.target.value)}
              placeholder={CONFIRMATION_PHRASE}
              className="w-full rounded-lg border border-red-900 bg-[var(--background)] px-3 py-2 text-sm text-[var(--foreground)] outline-none focus:border-red-700"
            />
            <label className="flex items-start gap-2 text-xs text-[var(--text-secondary)]">
              <input
                type="checkbox"
                checked={acknowledged}
                onChange={(e) => setAcknowledged(e.target.checked)}
                className="mt-0.5"
              />
              I understand this permanently deletes all business data and cannot be undone.
            </label>
            <div className="flex justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={closeModal}
                className="rounded-lg px-4 py-2 text-sm text-[var(--text-secondary)] hover:bg-[var(--surface-hover)]"
              >
                Cancel
              </button>
              <button
                type="button"
                disabled={!canConfirm}
                onClick={handleDelete}
                className="rounded-lg bg-red-800 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 transition-colors disabled:opacity-50"
              >
                {isDeleting ? "Deleting..." : "Delete Everything"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default DangerZonePanel;

'@

# -----------------------------------------------------------------
# 1. Storage bucket migration
# -----------------------------------------------------------------
$migrationDir = Join-Path $root "apps\backend\supabase\migrations"
Ensure-Dir $migrationDir
$migrationPath = Join-Path $migrationDir "0006_exports_bucket.sql"

if (Test-Path -LiteralPath $migrationPath) {
    Write-Host "0006_exports_bucket.sql already exists - skipping." -ForegroundColor Yellow
} else {
    Set-Content -LiteralPath $migrationPath -Value $migrationSql -NoNewline
    Write-Host "Created migration -> apps\backend\supabase\migrations\0006_exports_bucket.sql" -ForegroundColor Green
}

# -----------------------------------------------------------------
# 2. data-export edge function
# -----------------------------------------------------------------
$exportFnDir = Join-Path $root "apps\backend\supabase\functions\data-export"
Ensure-Dir $exportFnDir
$exportFnPath = Join-Path $exportFnDir "index.ts"

if (Test-Path -LiteralPath $exportFnPath) {
    Backup-File $exportFnPath
}
Set-Content -LiteralPath $exportFnPath -Value $exportFnTs -NoNewline
Write-Host "Created/updated -> apps\backend\supabase\functions\data-export\index.ts" -ForegroundColor Green

# -----------------------------------------------------------------
# 3. data-delete edge function
# -----------------------------------------------------------------
$deleteFnDir = Join-Path $root "apps\backend\supabase\functions\data-delete"
Ensure-Dir $deleteFnDir
$deleteFnPath = Join-Path $deleteFnDir "index.ts"

if (Test-Path -LiteralPath $deleteFnPath) {
    Backup-File $deleteFnPath
}
Set-Content -LiteralPath $deleteFnPath -Value $deleteFnTs -NoNewline
Write-Host "Created/updated -> apps\backend\supabase\functions\data-delete\index.ts" -ForegroundColor Green

# -----------------------------------------------------------------
# 4. Frontend panel components
# -----------------------------------------------------------------
$uiDir = Join-Path $root "apps\frontend\components\ui"
Ensure-Dir $uiDir

$exportPanelPath = Join-Path $uiDir "export-data-panel.tsx"
if (Test-Path -LiteralPath $exportPanelPath) { Backup-File $exportPanelPath }
Set-Content -LiteralPath $exportPanelPath -Value $exportPanelTsx -NoNewline
Write-Host "Created/updated -> apps\frontend\components\ui\export-data-panel.tsx" -ForegroundColor Green

$dangerPanelPath = Join-Path $uiDir "danger-zone-panel.tsx"
if (Test-Path -LiteralPath $dangerPanelPath) { Backup-File $dangerPanelPath }
Set-Content -LiteralPath $dangerPanelPath -Value $dangerPanelTsx -NoNewline
Write-Host "Created/updated -> apps\frontend\components\ui\danger-zone-panel.tsx" -ForegroundColor Green

# -----------------------------------------------------------------
# 5. Wire panels into Settings page
# -----------------------------------------------------------------
$settingsPath = Join-Path $root "apps\frontend\app\(dashboard)\settings\page.tsx"

if (-not (Test-Path -LiteralPath $settingsPath)) {
    Write-Host "ERROR: Could not find $settingsPath - panels created but NOT wired into Settings." -ForegroundColor Red
    Write-Host "Manually import and render <ExportDataPanel /> and <DangerZonePanel /> there." -ForegroundColor Yellow
    exit 0
}

$settingsContent = Get-Content -Raw -LiteralPath $settingsPath

if ($settingsContent -match "ExportDataPanel") {
    Write-Host "Settings page already wired up - skipping." -ForegroundColor Yellow
    exit 0
}

Backup-File $settingsPath

# --- Add imports: insert after the last existing "import ... from ...;" line
$importInsert = "import { ExportDataPanel } from `"@/components/ui/export-data-panel`";`r`nimport { DangerZonePanel } from `"@/components/ui/danger-zone-panel`";`r`n"

$importMatches = [regex]::Matches($settingsContent, '(?m)^import .+;\r?\n')
if ($importMatches.Count -eq 0) {
    Write-Host "ERROR: Could not find any import statements in settings/page.tsx - aborting import insertion." -ForegroundColor Red
    Write-Host "Panels were still created; add the imports and JSX manually." -ForegroundColor Yellow
    exit 0
}
$lastImport = $importMatches[$importMatches.Count - 1]
$insertPos = $lastImport.Index + $lastImport.Length
$settingsContent = $settingsContent.Substring(0, $insertPos) + $importInsert + $settingsContent.Substring($insertPos)

# --- Insert the two panels before the final closing of the component's
#     returned JSX. We look for the LAST occurrence of a closing
#     "</div>\n    );\n  }" style ending (generic, tolerant of indentation).
$closePattern = '(?s)(\s*</div>\s*\)\s*;\s*\}\s*)$'
if ($settingsContent -notmatch $closePattern) {
    Write-Host "WARNING: Could not find a safe insertion point at the end of the component." -ForegroundColor Yellow
    Write-Host "Imports were added, but you'll need to manually add:" -ForegroundColor Yellow
    Write-Host '  <ExportDataPanel />' -ForegroundColor Yellow
    Write-Host '  <DangerZonePanel />' -ForegroundColor Yellow
    Write-Host "inside the returned JSX of the Settings page." -ForegroundColor Yellow
    Set-Content -LiteralPath $settingsPath -Value $settingsContent -NoNewline
    exit 0
}

$panelInsert = @"

      <ExportDataPanel />
      <DangerZonePanel />
    </div>
  );
}
"@

$settingsContent = [regex]::Replace($settingsContent, $closePattern, $panelInsert, 1)

Set-Content -LiteralPath $settingsPath -Value $settingsContent -NoNewline
Write-Host "Wired ExportDataPanel + DangerZonePanel into Settings page." -ForegroundColor Green

Write-Host ""
Write-Host "Done. Next steps:" -ForegroundColor Cyan
Write-Host "  1. Double-check TABLE_MAP in data-export/index.ts and DELETE_ORDER in data-delete/index.ts" -ForegroundColor Cyan
Write-Host "     match your real table/column names (see supabase/migrations/0001_init_schema.sql)." -ForegroundColor Cyan
Write-Host "  2. Run: supabase db push   (applies the new exports-bucket migration)" -ForegroundColor Cyan
Write-Host "  3. Run: supabase functions deploy data-export" -ForegroundColor Cyan
Write-Host "     Run: supabase functions deploy data-delete" -ForegroundColor Cyan
Write-Host "  4. npm run build   to verify the frontend compiles." -ForegroundColor Cyan