-- Creates a private storage bucket for generated export files (csv/xlsx/pdf/docx).
-- Files are short-lived: accessed via signed URLs generated by the data-export function.

insert into storage.buckets (id, name, public)
values ('exports', 'exports', false)
on conflict (id) do nothing;

-- Allow the service role (used inside edge functions) full access.
-- Edge functions use the service role key, so no additional policy is
-- strictly required for them, but we add explicit policies for clarity
-- and in case authenticated users are ever given direct access later.

drop policy if exists "Service role manages exports" on storage.objects;
create policy "Service role manages exports"
  on storage.objects
  for all
  to service_role
  using (bucket_id = 'exports')
  with check (bucket_id = 'exports');
